### ISSUE TITLE
Failing tests due to missing OS interfaces

### ISSUE THREAD

**Issue by Rookfighter** [build2-packaging/SimpleBLE#2]
Hi @boris-kolpackov 

I have tagged some of the example applications as tests, such that a consumer has at least something he can use as a test. However, these "tests" fail on `bdep ci` (see https://ci.stage.build2.org/@6c041742-31fb-4324-a2f9-b1fd020bb0b2). If I want to publish this library to cppget, should I do something about this? Or is this acceptable?

**Comment by boris-kolpackov** [comment]
Yes, I think it's fine. Maybe we will do something about dbus (like we did about X) in the future.

**Comment by Rookfighter** [comment]
Published to staging queue, thanks!
